baseurl = "http://sequencer.io/"
languageCode = "en-us"
title = "Sequence"
theme = "ion"
copyright = "Dataence, LLC. All Rights Reserved."

[Author]
	name = "Jian Zhen"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
	description = "High Performance Log Analyzer and Parser"
	twitter = "https://twitter.com/trustpath"
	linkedin = "https://linkedin.com/in/zhenjl"
	github = "https://github.com/trustpath/sequence"
	disqus = "sequencer"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 10

[[menu.main]]
	name = "Github"
	url = "https://github.com/trustpath/sequence"
	weight = 20

[[menu.main]]
	name = "Manual"
	url = "/manual/introduction/"
	weight = 30

[[menu.main]]
	name = "Blog"
	url = "/blog/"
	weight = 40

[[menu.projects]]
	name = "SurgeMQ"
	url = "https://github.com/surgemq/surgemq"
	weight = 10

[[menu.projects]]
	name = "Sequence"
	url = "https://github.com/trustpath/sequence"
	weight = 20

[[menu.projects]]
	name = "Others Cool Projects"
	url = "https://github.com/surge"
	weight = 30

[[menu.sites]]
	name = "SurgeMQ Blog"
	url = "http://surgemq.com"
	weight = 10

[[menu.sites]]
	name = "Zen 3.1 Blog"
	url = "http://zhen.org"
	weight = 20

[[menu.manual]]
	name = "Overview"
	identifier = "overview"
	weight = 10

[[menu.manual]]
	name = "Sequence"
	identifier = "sequence"
	weight = 20

[[menu.manual]]
	name = "Configuration"
	identifier = "configuration"
	weight = 30

